using Lab2.Common.Analysing;

namespace Lab2.Application;

public static class Program
{
    public static void Main()
    {
        const string text =
            "MRGFNIATXZQVFFNUXFFYBTCETYXIIXGZKACJLRGKQYEIXOYYAUAPX YIJLHPRGVTSFPAYNNYURZOPHXWYXLFRNUTZBRFKAHFWFZESYUWZ MOLLBSBZBJHFPLXKHVIVMZTZHUIWAETIUEDFGLXDIEXIYJIUXPNNEI XABVCINTVCIEZYYDAZGZIWTYXJIKTRZLMFFKALGZNVKZXIIMXUUNA PGVXFUSMISKHVYVOCRVXRIWTYXZOIRFNUXZNXLDUDPZGVHVOWM OYJERLAUGLVTUXTHRBUQZTYTXORNKBASFFXGHQVDSHUYJSYHDYU WYXYYKHVTUCDACAHXSEVGJIEFZGLXRSBXSYKOEPPNYAKTUACEFYI LFWEAHCIAUALLZNXMVCKLRRHGFNXMOYUESKPM";
        var keyLength = CypherAnalyzer.GetKeyLength(text);
        var splited = CypherAnalyzer.SplitByColumns(text, keyLength);
        Console.WriteLine(splited);
    }
}