using Lab2.Common.Math;
using Lab2.Visionary.Statistics;

var text =
    "MRGFNIATXZQVFFNUXFFYBTCETYXIIXGZKACJLRGKQYEIXOYYAUAPXYIJLHPRGVTSFPAYNNYURZOPHXWYXLFRNUTZBRFKAHFWFZESYUWZMOLLBSBZBJHFPLXKHVIVMZTZHUIWAETIUEDFGLXDIEXIYJIUXPNNEIXABVCINTVCIEZYYDAZGZIWTYXJIKTRZLMFFKALGZNVKZXIIMXUUNAPGVXFUSMISKHVYVOCRVXRIWTYXZOIRFNUXZNXLDUDPZGVHVOWMOYJERLAUGLVTUXTHRBUQZTYTXORNKBASFFXGHQVDSHUYJSYHDYUWYXYYKHVTUCDACAHXSEVGJIEFZGLXRSBXSYKOEPPNYAKTUACEFYILFWEAHCIAUALLZNXMVCKLRRHGFNXMOYUESKPM";
    var gram = ThreeGrams.MostPopularThreeGram(text);
    var destinations = ThreeGrams.GetDestinations(text, gram);
    var gcd = Number.Gcd(destinations);
    Console.WriteLine(gcd);