using Lab2.Tests.Extensions;

namespace Lab2.Tests.ThreeGrams;

[TestClass]
public class DestinationsTests
{
    [TestMethod]
    public void ShouldBeCorrect()
    {
        const string text =
            "MRGFNIATXZQVFFNUXFFYBTCETYXIIXGZKACJLRGKQYEIXOYYAUAPXYIJLHPRGVTSFPAYNNYURZOPHXWYXLFRNUTZBRFKAHFWFZESYUWZMOLLBSBZBJHFPLXKHVIVMZTZHUIWAETIUEDFGLXDIEXIYJIUXPNNEIXABVCINTVCIEZYYDAZGZIWTYXJIKTRZLMFFKALGZNVKZXIIMXUUNAPGVXFUSMISKHVYVOCRVXRIWTYXZOIRFNUXZNXLDUDPZGVHVOWMOYJERLAUGLVTUXTHRBUQZTYTXORNKBASFFXGHQVDSHUYJSYHDYUWYXYYKHVTUCDACAHXSEVGJIEFZGLXRSBXSYKOEPPNYAKTUACEFYILFWEAHCIAUALLZNXMVCKLRRHGFNXMOYUESKPM";
        const string threeGram = "TYX";
        List<int> expected = [156, 210];
        var result = Common.Statistics.ThreeGrams.GetDestinations(text, threeGram);
        ListAsserting.AreListEqual(expected, result);
    }
}